// ===================================
// PRODUCT DATA - 100+ Products
// ===================================

const productsData = {
    electronics: [
        { id: 1, name: "Wireless Pro Headphones", price: 299.99, category: "electronics", rating: 4.8 },
        { id: 2, name: "Smart Watch Ultra", price: 449.99, category: "electronics", rating: 4.9 },
        { id: 3, name: "4K Action Camera", price: 379.99, category: "electronics", rating: 4.7 },
        { id: 4, name: "Wireless Earbuds Pro", price: 189.99, category: "electronics", rating: 4.6 },
        { id: 5, name: "Portable SSD 2TB", price: 199.99, category: "electronics", rating: 4.8 },
        { id: 6, name: "Gaming Mouse RGB", price: 79.99, category: "electronics", rating: 4.5 },
        { id: 7, name: "Mechanical Keyboard", price: 149.99, category: "electronics", rating: 4.7 },
        { id: 8, name: "Tablet Pro 12.9\"", price: 899.99, category: "electronics", rating: 4.9 },
        { id: 9, name: "Wireless Charger", price: 49.99, category: "electronics", rating: 4.4 },
        { id: 10, name: "Smart Speaker", price: 99.99, category: "electronics", rating: 4.6 },
        { id: 11, name: "Laptop Stand Aluminum", price: 59.99, category: "electronics", rating: 4.7 },
        { id: 12, name: "USB-C Hub 7-in-1", price: 69.99, category: "electronics", rating: 4.5 },
        { id: 13, name: "Webcam 4K", price: 129.99, category: "electronics", rating: 4.6 },
        { id: 14, name: "Bluetooth Speaker", price: 149.99, category: "electronics", rating: 4.8 },
        { id: 15, name: "Power Bank 20000mAh", price: 45.99, category: "electronics", rating: 4.5 },
        { id: 16, name: "LED Desk Lamp", price: 39.99, category: "electronics", rating: 4.6 },
        { id: 17, name: "Monitor 27\" 4K", price: 549.99, category: "electronics", rating: 4.8 },
        { id: 18, name: "Gaming Headset", price: 159.99, category: "electronics", rating: 4.7 },
        { id: 19, name: "Drawing Tablet", price: 279.99, category: "electronics", rating: 4.6 },
        { id: 20, name: "VR Headset", price: 399.99, category: "electronics", rating: 4.9 }
    ],
    fashion: [
        { id: 21, name: "Designer Sunglasses", price: 179.99, category: "fashion", rating: 4.7 },
        { id: 22, name: "Leather Jacket", price: 349.99, category: "fashion", rating: 4.8 },
        { id: 23, name: "Running Shoes Pro", price: 139.99, category: "fashion", rating: 4.6 },
        { id: 24, name: "Casual Backpack", price: 89.99, category: "fashion", rating: 4.5 },
        { id: 25, name: "Wool Scarf", price: 49.99, category: "fashion", rating: 4.4 },
        { id: 26, name: "Denim Premium Jeans", price: 119.99, category: "fashion", rating: 4.7 },
        { id: 27, name: "Cotton T-Shirt Pack", price: 39.99, category: "fashion", rating: 4.5 },
        { id: 28, name: "Winter Coat", price: 299.99, category: "fashion", rating: 4.8 },
        { id: 29, name: "Leather Belt", price: 59.99, category: "fashion", rating: 4.6 },
        { id: 30, name: "Sports Cap", price: 29.99, category: "fashion", rating: 4.4 },
        { id: 31, name: "Dress Shoes", price: 159.99, category: "fashion", rating: 4.7 },
        { id: 32, name: "Casual Sneakers", price: 89.99, category: "fashion", rating: 4.6 },
        { id: 33, name: "Handbag Designer", price: 449.99, category: "fashion", rating: 4.9 },
        { id: 34, name: "Wallet Leather", price: 79.99, category: "fashion", rating: 4.5 },
        { id: 35, name: "Watch Classic", price: 249.99, category: "fashion", rating: 4.8 },
        { id: 36, name: "Silk Tie", price: 39.99, category: "fashion", rating: 4.4 },
        { id: 37, name: "Dress Shirt", price: 69.99, category: "fashion", rating: 4.6 },
        { id: 38, name: "Yoga Pants", price: 54.99, category: "fashion", rating: 4.7 },
        { id: 39, name: "Swimming Trunks", price: 34.99, category: "fashion", rating: 4.5 },
        { id: 40, name: "Formal Blazer", price: 279.99, category: "fashion", rating: 4.8 }
    ],
    home: [
        { id: 41, name: "Air Purifier HEPA", price: 199.99, category: "home", rating: 4.7 },
        { id: 42, name: "Robot Vacuum", price: 349.99, category: "home", rating: 4.8 },
        { id: 43, name: "Coffee Maker Premium", price: 179.99, category: "home", rating: 4.6 },
        { id: 44, name: "Blender High-Speed", price: 129.99, category: "home", rating: 4.7 },
        { id: 45, name: "Electric Kettle", price: 49.99, category: "home", rating: 4.5 },
        { id: 46, name: "Toaster 4-Slice", price: 79.99, category: "home", rating: 4.4 },
        { id: 47, name: "Rice Cooker Smart", price: 99.99, category: "home", rating: 4.6 },
        { id: 48, name: "Air Fryer XL", price: 139.99, category: "home", rating: 4.8 },
        { id: 49, name: "Slow Cooker", price: 69.99, category: "home", rating: 4.5 },
        { id: 50, name: "Food Processor", price: 149.99, category: "home", rating: 4.7 },
        { id: 51, name: "Knife Set Professional", price: 189.99, category: "home", rating: 4.8 },
        { id: 52, name: "Cookware Set 10-Piece", price: 249.99, category: "home", rating: 4.6 },
        { id: 53, name: "Bedding Set King", price: 159.99, category: "home", rating: 4.7 },
        { id: 54, name: "Pillow Memory Foam", price: 59.99, category: "home", rating: 4.5 },
        { id: 55, name: "Towel Set Luxury", price: 79.99, category: "home", rating: 4.6 },
        { id: 56, name: "Shower Curtain", price: 29.99, category: "home", rating: 4.4 },
        { id: 57, name: "Bath Mat", price: 34.99, category: "home", rating: 4.5 },
        { id: 58, name: "Laundry Basket", price: 39.99, category: "home", rating: 4.3 },
        { id: 59, name: "Storage Organizer", price: 49.99, category: "home", rating: 4.6 },
        { id: 60, name: "Smart Thermostat", price: 179.99, category: "home", rating: 4.8 }
    ],
    beauty: [
        { id: 61, name: "Skincare Set Premium", price: 149.99, category: "beauty", rating: 4.8 },
        { id: 62, name: "Hair Dryer Professional", price: 129.99, category: "beauty", rating: 4.7 },
        { id: 63, name: "Makeup Brush Set", price: 79.99, category: "beauty", rating: 4.6 },
        { id: 64, name: "Face Cream Anti-Aging", price: 89.99, category: "beauty", rating: 4.7 },
        { id: 65, name: "Perfume Designer 100ml", price: 129.99, category: "beauty", rating: 4.9 },
        { id: 66, name: "Electric Shaver", price: 159.99, category: "beauty", rating: 4.6 },
        { id: 67, name: "Nail Care Kit", price: 39.99, category: "beauty", rating: 4.5 },
        { id: 68, name: "Hair Straightener", price: 99.99, category: "beauty", rating: 4.7 },
        { id: 69, name: "Facial Cleanser Brush", price: 69.99, category: "beauty", rating: 4.6 },
        { id: 70, name: "Massage Gun", price: 149.99, category: "beauty", rating: 4.8 },
        { id: 71, name: "LED Face Mask", price: 199.99, category: "beauty", rating: 4.7 },
        { id: 72, name: "Essential Oil Set", price: 49.99, category: "beauty", rating: 4.5 },
        { id: 73, name: "Bath Bomb Set", price: 29.99, category: "beauty", rating: 4.6 },
        { id: 74, name: "Makeup Mirror LED", price: 59.99, category: "beauty", rating: 4.7 },
        { id: 75, name: "Hair Curler", price: 79.99, category: "beauty", rating: 4.5 },
        { id: 76, name: "Moisturizer Organic", price: 45.99, category: "beauty", rating: 4.6 },
        { id: 77, name: "Sunscreen SPF 50", price: 24.99, category: "beauty", rating: 4.7 },
        { id: 78, name: "Body Lotion", price: 34.99, category: "beauty", rating: 4.5 },
        { id: 79, name: "Lip Gloss Set", price: 39.99, category: "beauty", rating: 4.6 },
        { id: 80, name: "Eye Cream", price: 69.99, category: "beauty", rating: 4.8 }
    ],
    sports: [
        { id: 81, name: "Yoga Mat Premium", price: 49.99, category: "sports", rating: 4.7 },
        { id: 82, name: "Dumbbell Set Adjustable", price: 179.99, category: "sports", rating: 4.8 },
        { id: 83, name: "Resistance Bands Set", price: 29.99, category: "sports", rating: 4.6 },
        { id: 84, name: "Jump Rope Speed", price: 19.99, category: "sports", rating: 4.5 },
        { id: 85, name: "Fitness Tracker", price: 99.99, category: "sports", rating: 4.7 },
        { id: 86, name: "Foam Roller", price: 34.99, category: "sports", rating: 4.6 },
        { id: 87, name: "Kettlebell 20kg", price: 59.99, category: "sports", rating: 4.5 },
        { id: 88, name: "Exercise Ball", price: 24.99, category: "sports", rating: 4.4 },
        { id: 89, name: "Pull-up Bar", price: 39.99, category: "sports", rating: 4.6 },
        { id: 90, name: "Bike Helmet", price: 79.99, category: "sports", rating: 4.7 },
        { id: 91, name: "Water Bottle Insulated", price: 29.99, category: "sports", rating: 4.5 },
        { id: 92, name: "Swimming Goggles", price: 24.99, category: "sports", rating: 4.6 },
        { id: 93, name: "Tennis Racket Pro", price: 149.99, category: "sports", rating: 4.8 },
        { id: 94, name: "Soccer Ball Official", price: 39.99, category: "sports", rating: 4.5 },
        { id: 95, name: "Basketball Premium", price: 49.99, category: "sports", rating: 4.6 },
        { id: 96, name: "Golf Club Set", price: 499.99, category: "sports", rating: 4.9 },
        { id: 97, name: "Running Shorts", price: 34.99, category: "sports", rating: 4.5 },
        { id: 98, name: "Sports Bra", price: 39.99, category: "sports", rating: 4.6 },
        { id: 99, name: "Gym Bag", price: 54.99, category: "sports", rating: 4.7 },
        { id: 100, name: "Protein Shaker", price: 19.99, category: "sports", rating: 4.4 }
    ]
};

// Flatten all products
window.allProducts = [
    ...productsData.electronics,
    ...productsData.fashion,
    ...productsData.home,
    ...productsData.beauty,
    ...productsData.sports
];
